### ISSUE TITLE
webpack/lib/util/identifier

### ISSUE THREAD

**Issue by timowevel1** [ndom91/timeoff#17]
Hey,

I receive webpack/lib/util/identifier when doing npm run build. Any idea on this?

`> Build error occurred
{ Error: Cannot find module 'webpack/lib/util/identifier'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.mod._resolveFilename (/root/timeoff/node_modules/next/dist/build/webpack/require-hook.js:96:28)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/root/timeoff/node_modules/mini-css-extract-plugin/dist/index.js:10:19)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12) code: 'MODULE_NOT_FOUND' }
`

Thank you in advance!

**Comment by ndom91** [comment]
@timololipop woah, didn't think anyone would be using this! Haha. 

Anyway, it seems it was an issue with an outdated package and the fact that Next.js moved from webpack4 to webpack5 by default with Next.js 11. 

I was able to reproduce the error, found a fix, and pushed an update to `main` just now.

Can you give that a try and let me know if it fixes the issue for you as well? Thanks!

**Comment by timowevel1** [comment]
I will give it a shot in a few days, thank you!!
